#!/usr/bin/env bash
# tendb console host bootstrap. Logs to /var/log/tendb-console-init.log.
# Package releases do NOT replace the instance: tendb-console-updater polls
# the S3 tarball's ETag and reinstalls in-place (~20s), so terraform replaces
# this host only for real infra changes (IAM, env template, instance type).
# Stack: Caddy :80/:443 (auto-HTTPS) -> oauth2-proxy :4180 (Google, domain
# allow-list) -> tendb console :${console_port} (loopback only).
set -euxo pipefail
exec > /var/log/tendb-console-init.log 2>&1

export DEBIAN_FRONTEND=noninteractive
for attempt in $(seq 1 30); do
  apt-get update && apt-get install -y ca-certificates curl gnupg unzip jq \
    debian-keyring debian-archive-keyring apt-transport-https && break
  echo "apt busy (attempt $attempt) — retrying"
  sleep 10
done

# AWS CLI v2
curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install

# Node 22 (NodeSource)
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs

# Caddy (official apt repo)
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
  | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
  > /etc/apt/sources.list.d/caddy-stable.list
apt-get update && apt-get install -y caddy

# oauth2-proxy (single Go binary)
curl -sSL -o /tmp/o2p.tgz \
  "https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${oauth2_proxy_version}/oauth2-proxy-v${oauth2_proxy_version}.linux-amd64.tar.gz"
tar -xzf /tmp/o2p.tgz -C /tmp
install -m 0755 "/tmp/oauth2-proxy-v${oauth2_proxy_version}.linux-amd64/oauth2-proxy" /usr/local/bin/oauth2-proxy

# The tendb package
%{ if pkg_s3_uri != "" ~}
aws s3 cp "${pkg_s3_uri}" /tmp/tendb.tgz
npm install -g /tmp/tendb.tgz
mkdir -p /var/lib/tendb-console
aws s3api head-object \
  --bucket "$(echo "${pkg_s3_uri}" | sed -E 's|^s3://([^/]+)/.*|\1|')" \
  --key "$(echo "${pkg_s3_uri}" | sed -E 's|^s3://[^/]+/||')" \
  --query ETag --output text > /var/lib/tendb-console/installed-etag || true

# In-place release channel: a new tarball in S3 reinstalls + restarts the
# console in ~20s — no instance replacement, no cert churn, no terraform.
cat > /usr/local/bin/tendb-console-updater.sh <<'UPDATER'
#!/usr/bin/env bash
set -u
URI="__PKG_S3_URI__"
BUCKET=$(echo "$URI" | sed -E 's|^s3://([^/]+)/.*|\1|')
KEY=$(echo "$URI" | sed -E 's|^s3://[^/]+/||')
MARKER=/var/lib/tendb-console/installed-etag
while true; do
  ETAG=$(aws s3api head-object --bucket "$BUCKET" --key "$KEY" --query ETag --output text 2>/dev/null || echo "")
  LAST=$(cat "$MARKER" 2>/dev/null || echo "")
  if [ -n "$ETAG" ] && [ "$ETAG" != "$LAST" ]; then
    echo "[$(date -u +%FT%TZ)] new package $ETAG — installing"
    if aws s3 cp "$URI" /tmp/tendb-update.tgz && npm install -g /tmp/tendb-update.tgz; then
      echo "$ETAG" > "$MARKER"
      systemctl restart tendb-console
      echo "[$(date -u +%FT%TZ)] release installed, console restarted"
    else
      echo "[$(date -u +%FT%TZ)] install failed — will retry"
      sleep 30
    fi
  fi
  sleep 15
done
UPDATER
sed -i "s|__PKG_S3_URI__|${pkg_s3_uri}|" /usr/local/bin/tendb-console-updater.sh
chmod 0755 /usr/local/bin/tendb-console-updater.sh

cat > /etc/systemd/system/tendb-console-updater.service <<'UNIT'
[Unit]
Description=tendb console in-place release updater
After=network-online.target

[Service]
ExecStart=/usr/local/bin/tendb-console-updater.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable --now tendb-console-updater
%{ else ~}
npm install -g "${npm_package_spec}"
%{ endif ~}

# ---------------------------------------------------------------------------
# Credentials — pulled via the instance profile, kept out of the trace log.
# /etc/tendb/env is re-generated by this script on every service start, so
# a token rotation only needs `systemctl restart tendb-console`.
# ---------------------------------------------------------------------------
mkdir -p /etc/tendb

# RDS CA bundle for the replication view's strict-TLS probes to Aurora.
# Best-effort: without it the console reports a clear TLS error, not a crash.
curl -fsSL --max-time 30 https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem \
  -o /etc/tendb/rds-global-bundle.pem || rm -f /etc/tendb/rds-global-bundle.pem
cat > /usr/local/bin/tendb-console-env.sh <<'FETCH'
#!/usr/bin/env bash
set -euo pipefail
REGION="${region}"
PREFIX="${engine_ssm_prefix}"
param() {
  aws ssm get-parameter --region "$REGION" --name "$PREFIX/$1" $${2:-} \
    --query Parameter.Value --output text
}
ENGINE_HOST=$(param host)
TOKEN=$(param verification-token --with-decryption)
DBNAME=$(param dbname)
# Optional upstream-replication endpoints (Aurora → Neon view). Absent params
# leave the vars empty and the console reports the feature unconfigured.
REPL_PUB=$(param replication/publisher-url --with-decryption 2>/dev/null || true)
REPL_SUB=$(param replication/subscriber-url --with-decryption 2>/dev/null || true)
OAUTH_JSON=$(aws secretsmanager get-secret-value --region "$REGION" \
  --secret-id "${oauth_secret_id}" --query SecretString --output text)
umask 077
{
  echo "TENDB_API_URL=http://$ENGINE_HOST:2345"
  echo "TENDB_TOKEN=$TOKEN"
  echo "TENDB_DATABASE=$DBNAME"
  # Region + prefix let the console reach SSM directly (snapshot schedule,
  # on-demand snapshot requests) even though its DBLab transport is direct.
  echo "TENDB_REGION=$REGION"
  echo "TENDB_SSM_PREFIX=$PREFIX"
  # Quoted: connection URLs can carry & in their query strings.
  if [ -n "$REPL_PUB" ]; then echo "TENDB_REPLICATION_PUBLISHER_URL='$REPL_PUB'"; fi
  if [ -n "$REPL_SUB" ]; then echo "TENDB_REPLICATION_SUBSCRIBER_URL='$REPL_SUB'"; fi
  # RDS CA bundle (fetched at provision) so TLS to Aurora verifies strictly.
  if [ -f /etc/tendb/rds-global-bundle.pem ]; then
    echo "NODE_EXTRA_CA_CERTS=/etc/tendb/rds-global-bundle.pem"
  fi
  echo "OAUTH2_PROXY_CLIENT_ID=$(jq -r .client_id <<<"$OAUTH_JSON")"
  echo "OAUTH2_PROXY_CLIENT_SECRET=$(jq -r .client_secret <<<"$OAUTH_JSON")"
} > /etc/tendb/env
# Cookie secret survives restarts, dies with the instance (sessions re-auth).
if [ ! -f /etc/tendb/cookie-secret ]; then
  head -c 32 /dev/urandom | base64 | tr -- '+/' '-_' > /etc/tendb/cookie-secret
fi
echo "OAUTH2_PROXY_COOKIE_SECRET=$(cat /etc/tendb/cookie-secret)" >> /etc/tendb/env
FETCH
chmod 0755 /usr/local/bin/tendb-console-env.sh

# ---------------------------------------------------------------------------
# systemd units. NOTE: EnvironmentFile= is read BEFORE ExecStartPre runs, so
# the fetch-then-source happens inside run wrappers instead — each (re)start
# gets fresh credentials.
# ---------------------------------------------------------------------------
cat > /usr/local/bin/tendb-console-run.sh <<'RUN'
#!/usr/bin/env bash
set -euo pipefail
/usr/local/bin/tendb-console-env.sh
set -a; . /etc/tendb/env; set +a
exec /usr/bin/tendb console --no-open --port ${console_port}
RUN
chmod 0755 /usr/local/bin/tendb-console-run.sh

cat > /usr/local/bin/oauth2-proxy-run.sh <<RUN
#!/usr/bin/env bash
set -euo pipefail
set -a; . /etc/tendb/env; set +a
exec /usr/local/bin/oauth2-proxy \
  --provider=google \
  --http-address=127.0.0.1:4180 \
  --redirect-url=https://${domain}/oauth2/callback \
  --upstream=http://127.0.0.1:${console_port} \
%{ for d in allowed_email_domains ~}
  --email-domain=${d} \
%{ endfor ~}
  --skip-provider-button=true \
  --reverse-proxy=true \
  --cookie-secure=true \
  --cookie-expire=12h \
  --cookie-refresh=1h
RUN
chmod 0755 /usr/local/bin/oauth2-proxy-run.sh

cat > /etc/systemd/system/tendb-console.service <<UNIT
[Unit]
Description=tendb console (loopback)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/tendb-console-run.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/oauth2-proxy.service <<UNIT
[Unit]
Description=oauth2-proxy (Google) for tendb console
After=tendb-console.service
Wants=tendb-console.service

[Service]
ExecStart=/usr/local/bin/oauth2-proxy-run.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/caddy/Caddyfile <<CADDY
{
  email ${acme_email}
}

${domain} {
  reverse_proxy 127.0.0.1:4180
}
CADDY

systemctl daemon-reload
systemctl enable --now tendb-console oauth2-proxy
systemctl restart caddy

echo "tendb-console-init complete"
